name: Create Blogger Post from Issue

# Issueが作られた(opened)ときに実行
on:
  issues:
    types: [opened]

jobs:
  post-to-blogger:
    runs-on: ubuntu-latest
    permissions:
      issues: read # Issueの内容を読み取るために必要です

    steps:
      # 最初にリポジトリの情報を読み込むおまじないです
      - name: Checkout repository
        uses: actions/checkout@v4

      # Issueの本文をファイルに書き出します
      - name: Write issue body to a markdown file
        run: echo "${{ github.event.issue.body }}" > issue.md
        shell: bash

      # MarkdownをHTMLに変換します
      # こちらがエラーの出ていたアクションの修正版です
      - name: Convert Markdown to HTML
        uses: athul/markdown-to-html@v1.3
        with:
          markdown_file: "issue.md"
          output_html_file: "post.html"

      # Bloggerに投稿します
      # こちらもエラーの出ていたアクションの修正版です
      - name: Post content to Blogger
        uses: masaki-mag/blogger-post-action@v1.1.0
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          blog_id: ${{ secrets.BLOGGER_BLOG_ID }}
          title: ${{ github.event.issue.title }}
          content_file: "post.html"
          is_draft: false
