name: Create Blogger Post from Issue

on:
  issues:
    types: [opened]

jobs:
  post-to-blogger:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Write issue body to a markdown file
        run: echo "$ISSUE_BODY" > issue.md
        env:
          ISSUE_BODY: ${{ github.event.issue.body }}

      - name: Install pandoc
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc

      - name: Convert Markdown to HTML
        run: pandoc issue.md -f markdown -t html -o post.html
      
      - name: Show HTML content for debugging
        run: |
          echo "--- HTML Content Preview ---"
          cat post.html
          echo "--------------------------"

      # ★★★★★ ここが最後の修正ポイントです！ ★★★★★
      - name: Authenticate to Google Cloud
        id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
          # Blogger APIを操作するための専用の権限（スコープ）を要求します
          scopes: 'https://www.googleapis.com/auth/blogger'

      - name: Create JSON and Post to Blogger
        run: |
          set -x
          cat << 'EOF' > create_payload.py
          import json, os, sys
          issue_title = sys.argv[1]
          html_content = open("post.html").read()
          payload = {
              "title": issue_title,
              "content": html_content
          }
          print(json.dumps(payload))
          EOF
          BODY_JSON=$(python create_payload.py "${{ github.event.issue.title }}")
          
          echo "--- JSON Payload Preview ---"
          echo "$BODY_JSON"
          echo "--------------------------"

          curl --fail -X POST \
            -H "Authorization: Bearer ${{ steps.auth.outputs.access_token }}" \
            -H "Content-Type: application/json" \
            -d "$BODY_JSON" \
            "https://www.googleapis.com/blogger/v3/blogs/${{ secrets.BLOGGER_BLOG_ID }}/posts/?isDraft=false"
